-- PROJETO SQL ESCOLAS
-- https://github.com/ErickVeronezi


-- CONSTRAINTS


ALTER TABLE ESCOLA ADD CONSTRAINT FK_ESCOLA_SEDE
FOREIGN KEY (FK_IDSEDE) REFERENCES SEDE(IDSEDE);
GO

ALTER TABLE ESCOLA_CURSO ADD CONSTRAINT FK_ESCOLA_CURSO
FOREIGN KEY (FK_IDESCOLA) REFERENCES ESCOLA(IDESCOLA);
GO

ALTER TABLE ESCOLA_CURSO ADD CONSTRAINT FK_CURSO_ESCOLA
FOREIGN KEY (FK_IDCURSO) REFERENCES CURSO(IDCURSO);
GO


ALTER TABLE ENDERECO_UNIDADE ADD CONSTRAINT FK_ENDERECO_ESCOLA
FOREIGN KEY (FK_IDESCOLA) REFERENCES ESCOLA(IDESCOLA);
GO


ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_ESCOLA
FOREIGN KEY (FK_IDESCOLA) REFERENCES ESCOLA(IDESCOLA);
GO


ALTER TABLE TELEFONE_FUNCIONARIO ADD CONSTRAINT FK_TELEFONE_FUNCIONARIO
FOREIGN KEY (FK_IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO);
GO


ALTER TABLE EXPEDIENTE ADD CONSTRAINT FK_EXPEDIENTE_FUNCIONARIO
FOREIGN KEY (FK_IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO);
GO

ALTER TABLE MATRICULA ADD CONSTRAINT FK_MATRICULA_CURSO
FOREIGN KEY (FK_IDCURSO) REFERENCES CURSO(IDCURSO);
GO


ALTER TABLE MATRICULA ADD CONSTRAINT FK_MATRICULA_ALUNO
FOREIGN KEY (FK_IDALUNO) REFERENCES ALUNO(IDALUNO);
GO

ALTER TABLE MATRICULA ADD CONSTRAINT FK_ESCOLA_MATRICULA
FOREIGN KEY (FK_IDESCOLA) REFERENCES ESCOLA(IDESCOLA)


ALTER TABLE TELEFONE_ALUNO ADD CONSTRAINT FK_TELEFONE_ALUNO
FOREIGN KEY (FK_IDALUNO) REFERENCES ALUNO(IDALUNO);
GO


ALTER TABLE ENDERECO_ALUNO ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY (FK_IDALUNO) REFERENCES ALUNO(IDALUNO);
GO


ALTER TABLE PRESENCA ADD CONSTRAINT FK_PRESENCA_ALUNO
FOREIGN KEY (FK_IDALUNO) REFERENCES ALUNO(IDALUNO);
GO
