-- PROJETO SQL ESCOLAS
-- https://github.com/ErickVeronezi


-- TABELAS

CREATE TABLE SEDE(
	IDSEDE INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30)
)
GO

CREATE TABLE CURSO(
	IDCURSO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	CARGA_HORARIA INT NOT NULL,
)
GO


CREATE TABLE ESCOLA(
	IDESCOLA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	FK_IDSEDE INT,
)
GO

CREATE TABLE ESCOLA_CURSO (
  IDESCOLA_CURSO INT PRIMARY KEY IDENTITY,
  FK_IDESCOLA INT,
  FK_IDCURSO INT
);
GO


CREATE TABLE ENDERECO_UNIDADE(
	IDENDERECO INT PRIMARY KEY IDENTITY,
	RUA VARCHAR(30) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	CEP CHAR(9) NOT NULL UNIQUE,
	FK_IDESCOLA INT
)
GO

ALTER TABLE ENDERECO_UNIDADE
ADD CONSTRAINT CK_ENDERECO_ESTADO CHECK (ESTADO IN('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'));
GO

CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	CPF CHAR(14) NOT NULL UNIQUE,
	CARGO VARCHAR(50) NOT NULL,
	DATA_CONTRATACAO DATE NOT NULL,
	FK_IDESCOLA INT 
)
GO

CREATE TABLE TELEFONE_FUNCIONARIO(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	NUMERO VARCHAR(15) NOT NULL UNIQUE,
	TIPO CHAR(3) NOT NULL,
	FK_IDFUNCIONARIO INT
)
GO

ALTER TABLE TELEFONE_FUNCIONARIO
ADD CONSTRAINT CK_TELEFONE_TIPO CHECK (TIPO IN('RES','COM','CEL'));
GO

CREATE TABLE EXPEDIENTE(
	IDEXPEDIENTE INT PRIMARY KEY IDENTITY,
	HORARIO_EXPEDIENTE TIME NOT NULL,
	FK_IDFUNCIONARIO INT
)
GO


CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	CPF CHAR(14) NOT NULL UNIQUE
)
GO

CREATE TABLE MATRICULA(
	IDMATRICULA INT PRIMARY KEY IDENTITY,
	TIPO VARCHAR(30) NOT NULL,
	DATA_INICIO DATE,
	DATA_FIM DATE,
	STATUS VARCHAR(15) NOT NULL,
	FK_IDCURSO INT,
	FK_IDALUNO INT,
	FK_IDESCOLA INT
)
GO

ALTER TABLE MATRICULA
ADD CONSTRAINT CK_MATRICULA_STATUS CHECK (STATUS IN('MATRICULADO','PENDENTE'));
GO



CREATE TABLE TELEFONE_ALUNO(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	NUMERO VARCHAR (15) NOT NULL,
	TIPO CHAR(3) NOT NULL,
	FK_IDALUNO INT
)
GO

CREATE TABLE ENDERECO_ALUNO(
	IDENDERECO INT PRIMARY KEY IDENTITY,
	RUA VARCHAR(30) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	CEP CHAR(9) NOT NULL,
	FK_IDALUNO INT
)
GO


CREATE TABLE PRESENCA(
	IDPRESENCA INT PRIMARY KEY IDENTITY,
	FREQUENCIA VARCHAR(15) NOT NULL,
	DATA DATE DEFAULT GETDATE(),
	FK_IDALUNO INT
)
GO

