-- PROJETO SQL ESCOLAS
-- https://github.com/ErickVeronezi


-- LISTA DE VIEWS

CREATE VIEW V_RELATORIO_ALUNOS_SIMPLIFICADO AS
SELECT	A.NOME,
		A.EMAIL,
		C.NOME AS CURSO,
		M.DATA_INICIO AS INICIO_CURSO,
		T.NUMERO,
		T.TIPO AS TIPO_NUMERO,
		E.CIDADE,
		ES.NOME AS ESCOLA
FROM ALUNO A
JOIN MATRICULA M ON A.IDALUNO = M.FK_IDALUNO
JOIN CURSO C ON M.FK_IDCURSO = C.IDCURSO
LEFT JOIN ENDERECO_ALUNO E ON A.IDALUNO = E.FK_IDALUNO
LEFT JOIN TELEFONE_ALUNO T ON A.IDALUNO = T.FK_IDALUNO
JOIN ESCOLA_CURSO EC ON C.IDCURSO = EC.FK_IDCURSO
JOIN ESCOLA ES ON EC.FK_IDESCOLA = ES.IDESCOLA;




CREATE VIEW V_FUNCIONARIOS_ESCOLA AS
SELECT 
    F.IDFUNCIONARIO,
    F.NOME,
    F.CARGO,
    T.NUMERO,
    T.TIPO AS TIPO_TELEFONE,
    F.DATA_CONTRATACAO,
    E.NOME AS ESCOLA
FROM FUNCIONARIO F
JOIN ESCOLA E ON F.FK_IDESCOLA = E.IDESCOLA
LEFT JOIN TELEFONE_FUNCIONARIO T ON T.FK_IDFUNCIONARIO = F.IDFUNCIONARIO;




CREATE VIEW V_CURSOS_POR_ESCOLA AS
SELECT 
    E.NOME AS ESCOLA,
    C.NOME AS CURSO,
    C.CARGA_HORARIA

FROM ESCOLA_CURSO EC
JOIN ESCOLA E ON EC.FK_IDESCOLA = E.IDESCOLA
JOIN CURSO C ON EC.FK_IDCURSO = C.IDCURSO;





CREATE VIEW V_ALUNOS_MATRICULA_PENDENTE AS
SELECT 
    A.NOME AS ALUNO,
    M.STATUS,
    M.DATA_INICIO,
    M.DATA_FIM
FROM ALUNO A
JOIN MATRICULA M ON A.IDALUNO = M.FK_IDALUNO
WHERE M.STATUS = 'PENDENTE' OR (M.DATA_FIM IS NOT NULL AND M.DATA_FIM < GETDATE());





CREATE VIEW V_ALUNOS_MATRICULADOS AS
SELECT 
    A.NOME AS ALUNO,
    M.STATUS,
    M.DATA_INICIO,
    M.DATA_FIM
FROM ALUNO A
JOIN MATRICULA M ON A.IDALUNO = M.FK_IDALUNO
WHERE M.STATUS = 'MATRICULADO'





CREATE VIEW V_MEDIA_CARGA_HORARIA_POR_ESCOLA AS
SELECT 
    E.NOME AS ESCOLA,
    AVG(C.CARGA_HORARIA) AS MEDIA_CARGA_HORARIA
FROM ESCOLA E
JOIN ESCOLA_CURSO EC ON E.IDESCOLA = EC.FK_IDESCOLA
JOIN CURSO C ON C.IDCURSO = EC.FK_IDCURSO
GROUP BY E.NOME;





CREATE VIEW V_PRESENCA_POR_ALUNO AS
SELECT 
    A.NOME AS ALUNO,
    COUNT(P.IDPRESENCA) AS TOTAL_REGISTROS,
    SUM(CASE WHEN P.FREQUENCIA = 'PRESENTE' THEN 1 ELSE 0 END) AS PRESENTES,
    SUM(CASE WHEN P.FREQUENCIA = 'FALTA' THEN 1 ELSE 0 END) AS FALTAS
FROM ALUNO A
JOIN PRESENCA P ON A.IDALUNO = P.FK_IDALUNO
GROUP BY A.NOME;

CREATE VIEW V_FUNCIONARIOS_POR_ESCOLA AS
SELECT 
    E.NOME AS ESCOLA,
    COUNT(F.IDFUNCIONARIO) AS TOTAL_FUNCIONARIOS
FROM ESCOLA E
JOIN FUNCIONARIO F ON E.IDESCOLA = F.FK_IDESCOLA
GROUP BY E.NOME;



